version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-development:
        dependency-type: development

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/admin
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/cyberlab
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/homelab
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/ailab
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/auth
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
